package dev.rishabkumar.prism.ai;

import dev.rishabkumar.prism.github.GitHubService;
import io.quarkus.logging.Log;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.kohsuke.github.GHPullRequest;
import org.kohsuke.github.GHRepository;

import java.io.IOException;

@ApplicationScoped
public class SummaryService {

    @Inject
    SummaryAI summaryAI;

    @Inject
    GitHubService gitHubService;

    public void summarize(GHPullRequest pullRequest, GHRepository repository) throws IOException {
        String repoName = gitHubService.getRepoName(repository);
        int prNumber = pullRequest.getNumber();

        Log.infof("[%s#%d] Summary requested", repoName, prNumber);

        String diff = gitHubService.fetchDiff(pullRequest);

        if (diff == null || diff.isBlank()) {
            Log.warnf("[%s#%d] Empty diff, skipping summary", repoName, prNumber);
            gitHubService.postReviewComment(pullRequest, "Could not generate a summary. Please try again.");
            return;
        }

        Log.infof("[%s#%d] Sending %d char diff to AI for summary", repoName, prNumber, diff.length());
        String summary = summaryAI.summarize(diff);

        if (summary == null || summary.isBlank()) {
            Log.warnf("[%s#%d] AI returned empty summary", repoName, prNumber);
            gitHubService.postReviewComment(pullRequest, "Could not generate a summary. Please try again.");
            return;
        }

        String comment = """
                ## PR Summary

                %s

                ---
                *Generated by PRism*
                """.formatted(summary);

        gitHubService.postReviewComment(pullRequest, comment);
        Log.infof("[%s#%d] Summary posted", repoName, prNumber);
    }
}
