package dev.rishabkumar.prism.github;

import dev.rishabkumar.prism.ai.SummaryService;
import dev.rishabkumar.prism.review.ReviewService;
import io.quarkiverse.githubapp.event.IssueComment;
import io.quarkus.logging.Log;
import jakarta.inject.Inject;
import org.eclipse.microprofile.context.ManagedExecutor;
import org.kohsuke.github.GHEventPayload;
import org.kohsuke.github.GHPullRequest;

import java.io.IOException;

public class IssueCommentHandler {

    @Inject
    ReviewService reviewService;

    @Inject
    SummaryService summaryService;

    @Inject
    GitHubService gitHubService;

    @Inject
    ManagedExecutor executor;

    void onIssueComment(@IssueComment.Created GHEventPayload.IssueComment payload) throws IOException {
        String body = payload.getComment().getBody();
        if (body == null) {
            return;
        }

        String command = body.trim().toLowerCase();

        if (!payload.getIssue().isPullRequest()) {
            return;
        }

        GHPullRequest pullRequest = payload.getRepository().getPullRequest(payload.getIssue().getNumber());
        var repository = payload.getRepository();

        if (command.equals("/review")) {
            executor.submit(() -> {
                try {
                    reviewService.review(pullRequest, repository);
                } catch (Exception e) {
                    Log.errorf(e, "Async /review failed for PR #%d", pullRequest.getNumber());
                }
            });
        } else if (command.equals("/summary")) {
            executor.submit(() -> {
                try {
                    handleSummary(pullRequest);
                } catch (Exception e) {
                    Log.errorf(e, "Async /summary failed for PR #%d", pullRequest.getNumber());
                }
            });
        }
    }

    private void handleSummary(GHPullRequest pullRequest) throws IOException {
        int prNumber = pullRequest.getNumber();
        Log.infof("PR #%d] Summary requested", prNumber);

        String diff = gitHubService.fetchDiff(pullRequest);
        String summary = summaryService.summarize(diff);

        if (summary == null) {
            gitHubService.postReviewComment(pullRequest, "Could not generate a summary. Please try again.");
            return;
        }

        String comment = """
                ## PR Summary

                %s

                ---
                *Generated by PRism*
                """.formatted(summary);

        gitHubService.postReviewComment(pullRequest, comment);
        Log.infof("[PR #%d] Summary posted", prNumber);
    }
}
