package dev.rishabkumar.prism.ai.service;

import dev.rishabkumar.prism.ai.client.SummaryAI;
import dev.rishabkumar.prism.github.service.GitHubService;
import dev.rishabkumar.prism.ratelimit.model.RateLimitResult;
import dev.rishabkumar.prism.ratelimit.model.RateLimitStatus;
import dev.rishabkumar.prism.ratelimit.service.RateLimitService;
import io.quarkus.logging.Log;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.kohsuke.github.GHPullRequest;
import org.kohsuke.github.GHRepository;

import java.io.IOException;

@ApplicationScoped
public class SummaryService {

    @Inject
    SummaryAI summaryAI;

    @Inject
    GitHubService gitHubService;

    @Inject
    RateLimitService rateLimitService;

    public void summarize(GHPullRequest pullRequest, GHRepository repository, long installationId, String accountName) throws IOException {
        String repoName = gitHubService.getRepoName(repository);
        int prNumber = pullRequest.getNumber();

        Log.infof("[%s#%d] Summary requested", repoName, prNumber);

        RateLimitResult limitResult = rateLimitService.check(installationId, accountName);
        if (limitResult.isExceeded()) {
            Log.warnf("[%s#%d] Review budget exhausted for installation %d (%d/%d monthly, %d/%d daily)",
                    repoName, prNumber, installationId,
                    limitResult.reviewsUsed(), limitResult.reviewBudget(),
                    limitResult.dailyReviewsUsed(), limitResult.dailyReviewBudget());
            gitHubService.postReviewComment(pullRequest, buildRateLimitExceededComment(limitResult));
            return;
        }

        String diff = gitHubService.fetchDiff(pullRequest);

        if (diff == null || diff.isBlank()) {
            Log.warnf("[%s#%d] Empty diff, skipping summary", repoName, prNumber);
            gitHubService.postReviewComment(pullRequest, "Could not generate a summary. Please try again.");
            return;
        }

        Log.infof("[%s#%d] Sending %d char diff to AI for summary", repoName, prNumber, diff.length());
        String summary = summaryAI.summarize(diff);

        if (summary == null || summary.isBlank()) {
            Log.warnf("[%s#%d] AI returned empty summary", repoName, prNumber);
            gitHubService.postReviewComment(pullRequest, "Could not generate a summary. Please try again.");
            return;
        }

        rateLimitService.record(installationId);

        String comment = buildSummaryComment(summary, limitResult);
        gitHubService.postReviewComment(pullRequest, comment);
        Log.infof("[%s#%d] Summary posted", repoName, prNumber);
    }

    private String buildSummaryComment(String summary, RateLimitResult limit) {
        StringBuilder sb = new StringBuilder();
        sb.append("## PR Summary\n\n").append(summary).append("\n\n---\n*Generated by PRism*");

        if (limit.status() == RateLimitStatus.WARNING) {
            sb.append("""


                    > **Usage warning:** This repository has used %d%% of its monthly review budget (%s tier: %d reviews/month). \
                    Reviews will be blocked when the budget is exhausted."""
                    .formatted(limit.percentUsed(), limit.tier(), limit.reviewBudget()));
        }

        return sb.toString();
    }

    private String buildRateLimitExceededComment(RateLimitResult limit) {
        if (limit.isDailyExceeded()) {
            return """
                    ## PRism - Daily Limit Reached

                    This repository has used all %d reviews allowed today (%s plan).
                    Reviews will resume automatically tomorrow.

                    To increase your daily limit, upgrade your PRism plan.
                    """.formatted(limit.dailyReviewBudget(), limit.tier());
        }
        return """
                ## PRism - Monthly Budget Exhausted

                This repository has used all %d reviews included in the %s plan this month.
                Reviews and summaries are paused until the 1st of next month.

                To increase your limit, upgrade your PRism plan.
                """.formatted(limit.reviewBudget(), limit.tier());
    }
}
